config/routes.rb
Html5Weiqi::Application.routes.draw do
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/signin' => 'sessions#new', :as => :signin
  match '/signup' => 'users#new', :as => :signup
  match '/duel' => 'games#duel', :as => :duel
  match '/watch' => 'games#index', :as => :index
  match '/games/laoqipan_:id.sgf' => 'games#sgf', :format => "sgf", :as => "game_sgf"
  match '/records' => 'games#records', :as => :records
  match '/upload_sgf' => 'games#upload_sgf', :as => :upload_sgf
  
  match '/reset_password' => 'users#reset_password', :as => :reset_password
  match '/recover_password' => 'users#recover_password', :as => :recover_password
  match '/recovery_session' => 'sessions#recovery', :as => :recovery_session
  
  match '/confirm_email' => 'sessions#confirm_email', :as => :confirm_email
  match '/validate_email' => 'users#validate_email', :as => :validate_email

  # match '/auth', :to => 'authentications#index'
  # match '/auth/:provider/callback', :to => 'authentications#create'
  
  match '/handle_notify', :to => 'sessions#handle_notify', :as => :handle_notify
  match '/notify', :to => 'notifications#notify'
  match '/current_games', :to => 'games#current_games'
  match '/challenge', :to => 'games#gnugo_challenge', :as => :challenge
  match '/blogs' => 'broadcasts#blogs', :as => :blogs
  
  resources :broadcasts

  resources :sessions
  resources :notices
  resources :relationships, :only => [:create, :destroy]
  
  resources :users do
    resources :invitations
    resources :authentications
    member do
      get :following, :followers
    end
  end
  
  resources :games do
    resources :moves
    resources :comments
  end

  root :to => "pages#index"
  
  if ['development', 'test'].include? Rails.env
    mount Jasminerice::Engine => '/jasmine'
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation, :guest, :rank, :wins, :loses, :open_for_play, :avatar, :salt, :role, :last_request_at, :email_confirmed, :notify_pendding_move, :connected, :level
  attr_accessor :password
  
  before_save :make_password
  
  has_many :current_games, :class_name => "Game", :foreign_key => "current_player_id", :conditions => "status != 1 and mode != 0", :order => "updated_at DESC", :limit => 4
  has_many :comments, :dependent => :destroy
  has_attached_file :avatar, :styles => { :small => "24x24>", :medium => "48x48>" }
  has_many :authentications, :dependent => :destroy
  has_many :pro_games, :class_name => 'Game', :foreign_key => "uploader"
  has_many :relationships, :foreign_key => "follower_id", :dependent => :destroy
  has_many :following, :through => :relationships, :source => :followed
  has_many :reverse_relationships, :foreign_key => "followed_id", 
                                   :class_name => "Relationship",
                                   :dependent => :destroy
  has_many :followers, :through => :reverse_relationships, :source => :follower
  
  validates_presence_of :name
  validates_length_of :name, :within => 2..9, :message => I18n.t(:name_length_msg)
  validates_presence_of :email
  validates_uniqueness_of :name, :email, :allow_blank => true, :case_sensitive => false, :message => I18n.t(:unique_msg)
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i, :allow_blank => true, :message => I18n.t(:invalid_email_msg)
  validates_presence_of :password, :on => :create
  validates_confirmation_of :password
  validates_length_of :password, :within => 6..20, :allow_blank => true, :message => I18n.t(:password_length_msg)
  validates_attachment_size :avatar, :less_than => 128.kilobytes
  validates_attachment_content_type :avatar, :content_type => ['image/jpeg', 'image/png']
  
  scope :on_play_list, lambda { |user_id| where("id != #{user_id} and open_for_play = true").order("last_request_at DESC") }
  
  def self.authenticate(login, pass)
    @user = find(:first, :conditions => ["lower(name) = ?", login.downcase]) || find(:first, :conditions => ["lower(email) = ?", login.downcase])
    return @user if @user && @user.has_password?(pass)
  end
  
  def self.authenticate_with_salt(user_id, user_salt)
    user = User.find_by_id(user_id)
    user && user.salt == user_salt ? user : nil
  end
  
  def has_password?(pass)
    self.encrypted_password == encrypt_password(pass)
  end
  
  def following?(followed)
    if relationships.find_by_followed_id(followed)
      return true
    else
      return false
    end
  end
  
  def follow!(followed)
    relationships.create!(:followed_id => followed.id)
  end
  
  def unfollow!(followed)
    relationships.find_by_followed_id(followed).destroy
  end
  
  def feed
    Game.from_users_followed_by(self)
  end
  
  def win_rate
    r = sprintf("%.2f", wins.to_f/(wins+loses))
    r.to_f
  end
  
  def online?
    connected > 0
  end
  
  def admin?
    role.to_i == 2
  end
  
  def robot?
    gnugo? || fuego?
  end
  
  def gnugo?
    role.to_i == 98
  end
  
  def fuego?
    role.to_i == 99
  end
  
  private
    def make_password
      unless password.blank?
        self.salt = BCrypt::Engine.generate_salt
        self.encrypted_password = encrypt_password(password)
      end
    end
  
    def encrypt_password(pass)
      BCrypt::Engine.hash_secret(pass, salt)
    end
end


# == Schema Information
#
# Table name: users
#
#  id                   :integer         not null, primary key
#  name                 :string(255)
#  email                :string(255)
#  encrypted_password   :string(255)
#  salt                 :string(255)
#  created_at           :datetime
#  updated_at           :datetime
#  wins                 :integer         default(0)
#  loses                :integer         default(0)
#  points               :integer         default(0)
#  open_for_play        :boolean         default(TRUE)
#  avatar_file_name     :string(255)
#  avatar_content_type  :string(255)
#  avatar_file_size     :integer
#  avatar_updated_at    :datetime
#  last_request_at      :datetime
#  role                 :integer         default(0)
#  email_confirmed      :boolean         default(FALSE)
#  notify_pendding_move :boolean         default(FALSE)
#  connected            :integer         default(0)
#  level                :integer         default(0)
#

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :login_required, :only => [:edit, :update, :validate_email, :following, :followers, :index]
  before_filter :ensure_not_logged_in, :only => [:reset_password, :recover_password]
  
  def new
    if user_signed_in?
      flash[:notice] = I18n.t(:update_your_profile)
      redirect_to edit_user_url(current_user)
    end
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in(@user)
      redirect_to user_path(@user)
    else
      flash.now[:error] = @user.errors.full_messages
      render :action => 'new'
    end
  end
  
  def show
    @user = User.find(params[:id])
    
    if user_signed_in? and current_user == @user
      @feed_items = current_user.feed.page(params[:page]).per(7)
    else
      @feed_items = Game.current_games(@user.id).page(params[:page]).per(7)
    end

    @current_games = Game.current_games(@user.id).page(params[:current_games_page]).per(4)      
    @pro_game = Game.uploads.first
    
  end
  
  def index
    @users = User.page(params[:page]).per(19)
  end
  
  def edit
    @user = current_user
    if params[:email]
      @user.email = params[:email]
    end
  end
  
  def update
    @user = current_user
    @attr = params[:user]
    if @attr[:open_for_play] == "true"
      @attr.merge!(:open_for_play => true)
    else
      @attr.merge!(:open_for_play => false)
    end
    
    @user.attributes = @attr
    if @user.save
      flash[:success] = I18n.t("profile_has_been_updated")
      redirect_to(user_path(@user))
    else
      flash.now[:error] = @user.errors.full_messages
      render "edit"
    end
  end
  
  def reset_password
  end
  
  def recover_password
    user = User.find_by_email(params[:user][:email])
    if user
      Mailer.recovery(:key => Crypto.encrypt("#{user.id}:#{user.salt}"),
                      :email => user.email, 
                      :domain => request.env['HTTP_HOST']).deliver
      redirect_to signin_url, :notice => t(:recovery_email_sent)
    else
      redirect_to reset_password_url, :alert => t(:email_user_not_exists)
    end
  end
  
  def validate_email
    user = current_user
    if user
      Mailer.confirm(:key => Crypto.encrypt("#{user.id}:#{user.salt}"),
                     :email => user.email, 
                     :domain => request.env['HTTP_HOST']).deliver
      redirect_to user_path(user), :notice => t(:confirmation_email_sent)
    end
  end
  
  def following
    @user = User.find(params[:id])
    @users = @user.following.page(params[:page]).per(25)
    @action = I18n.t("is_following")
    respond_to do |format|
      format.html { render 'show_follow' }
    end
  end
  
  def followers
    @user = User.find(params[:id])
    @users = @user.followers.page(params[:page]).per(25)
    @action = I18n.t("s_followers")
    respond_to do |format|
      format.html { render 'show_follow' }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def uploader?(user)
    user.role.to_i == 1
  end
end

app/views/users/_feed.html.erb
<div class="user_feeds">
<% if @feed_items.empty? %>
	<h3><%= t(".following_users_feed_will_show_here") %></h3>
<% else %>
	<%= render :partial => 'shared/feed_item', :collection => @feed_items %>
	<div class="paginate">
		<%= paginate @feed_items %>
	</div>
<% end %>
</div>

app/views/users/_follow.html.erb
<%= form_for current_user.relationships.build(:followed_id => object.id), :remote => true do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
	<div class="action"><%= f.submit t(".follow") %></div>
<% end %>

app/views/users/_follow_button.html.erb
<span id="user_<%= object.id %>" class="follow_button">
	<% if user_signed_in? %>
		<% if current_user.following?(object) %>
			<%= render 'users/unfollow', :object => object %>
		<% elsif current_user != object %>
			<%= render 'users/follow', :object => object %>
		<% end %>
	<% end %>
</span>

app/views/users/_form.html.erb
<%= render "shared/errors_messages" %>

<%= form_for @user, :html => { :multipart => true, :class => "nice" } do |f| %>

<%= f.label :name, t(".username") %>
<%= f.text_field :name, :class => 'input-text' %>

<%= f.label :email, t(".email") %>
<%= f.text_field :email, :class => 'input-text' %>

<%= f.label :password, t(".password") %>
<%= f.password_field :password, :class => 'input-text' %>

<%= f.label :password_confirmation, t(".confirm") %>
<%= f.password_field :password_confirmation, :class => 'input-text' %>

<br/>
<%= f.radio_button :open_for_play, "true" %>
<%= t(".open_for_play") %><br/>
<%= f.radio_button :open_for_play, "false" %>
<%= t(".close_for_play") %><br/>
<br/>

<%= f.label t(:upload_image) %>
<%= f.file_field :avatar %>

<div class="divider"></div>
<div class="alert-box warning">
  <%= t(:image_notice) %>
</div>

<% if !@user.email_confirmed %>
  <p><%= link_to t(".confirm_email"), validate_email_url %></p>
<% end %>

<%= f.submit t(".create") %>
<% end %>

app/views/users/_list.html.erb
<% object.each do |u| %>
	<div class="player">
		<div class="player_avatar">
			<%= link_to player_image_tag(u), u, :class => 'select_avatar' %>
			<%= link_to t(:start_duel), new_game_path(:opponent => u.name), :class => 'select_link nice black radius button' %>
		</div>
		<div class="player_details">
			<h4><%= u.name %></h4>
			<%= render 'users/follow_button', :object => u %>
			<p>
				<span><%= t :wins %><%= u.wins %></span>
				<span><%= t :loses %><%= u.loses %></span><br/>
				<%= time_ago_in_words u.last_request_at if u.last_request_at %>
			</p>
		</div>
	</div>
<% end %>

app/views/users/_profile.html.erb
<div class="user_profile">
	<%= player_image_tag(@user) %>
	<%= @user.name %>
	<% if correct_user?(@user) %>
		<%= link_to t(:settings), edit_user_path(@user) %>
		<%= link_to t(:start_a_game), duel_path %>
	<% else %>
		<% if user_signed_in? and current_user != @user %>
		  <%= link_to t(:start_duel), new_game_path(:opponent => @user.name) %>
			<div id="follow_form">
				<%= render 'users/follow_button', :object => @user %>
			</div>
		<% end %>
	<% end %>
</div>

<div class="user_social">
	<span class="stat">
		<%= t(".following") %>
		<span id="following">
			<%= link_to @user.following.count, following_user_path(@user) %>
		</span>
	</span>
	<span class="stat">
		<%= t(".followers") %>
		<span id="follower">
			<%= link_to @user.followers.count, followers_user_path(@user) %>
		</span>
	</span>
</div>

app/views/users/_unfollow.html.erb
<%= form_for current_user.relationships.find_by_followed_id(object.id), :html => { :method => :delete }, :remote => true do |f| %>
  <div class="action"><%= f.submit t(".unfollow") %></div>
<% end %>

app/views/users/edit.html.erb
<div class="fixed_edit show">
	<%= render "form" %>
</div>

app/views/users/index.html.erb
<div class="pagination">
	<%= paginate @users %>
</div>
<%= render "list", :object => @users %>

app/views/users/new.html.erb
<div class="fixed show">
  <div>
    <%= render "shared/errors_messages" %>
    <h3><%= t ".new_user" %></h3>
    <%= form_for @user, :html => { :multipart => true, :class => 'nice' } do |f| %>

    <%= f.label :name, t(".username") %>
    <%= f.text_field :name, :class => 'input-text', :autocomplete => :off %><br/>

    <%= f.label :email, t(".email") %>
    <%= f.text_field :email, :class => 'input-text', :autocomplete => :off %><br/>

    <%= f.label :password, t(".password") %>
    <%= f.password_field :password, :class => 'input-text' %><br/>

    <%= f.label :password_confirmation, t(".confirm") %>
    <%= f.password_field :password_confirmation, :class => 'input-text' %><br/>

    <%= f.radio_button :open_for_play, "true" %>
    <%= t(".open_for_play") %><br/>
    <%= f.radio_button :open_for_play, "false" %>
    <%= t(".close_for_play") %><br/><br/>

    <%= f.label t(:upload_image) %>
    <%= f.file_field :avatar %><br/><br/>

    <div class="alert-box warning"><%= t(:image_notice) %></div>

    <%= f.submit t(".create") %>
<% end %>
</div>
</div>

app/views/users/reset_password.html.erb
<div class="fixed show">
  <%= render "shared/errors_messages" %>
  <%= form_for :user, :url => recover_password_url do |f| %>

    <%= f.label t(:email_to_reset) %>
    <%= f.text_field :email %><br/>

    <%= f.submit t(:reset_password) %>

  <% end %>
</div>

app/views/users/show.html.erb
<%= render "shared/errors_messages" %>
<%= render "shared/other_messages" %>

<div class="relative">
	<%= render "shared/side_bar" %>
	<%= render "profile" %>
	<%= render "feed" %>
</div>

app/views/users/show_follow.html.erb
<div class="show_follow">
	<h3>
		<%= @user.name %>
		<%= @action %>
	</h3>
	<% unless @users.empty? %>
		<%= render "users/list", :object => @users %>
	<% end %>
</div>

<div class="paginate">
	<%= paginate @users %>
</div>