config/routes.rb
Html5Weiqi::Application.routes.draw do
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/signin' => 'sessions#new', :as => :signin
  match '/signup' => 'users#new', :as => :signup
  match '/duel' => 'games#duel', :as => :duel
  match '/watch' => 'games#index', :as => :index
  match '/games/laoqipan_:id.sgf' => 'games#sgf', :format => "sgf", :as => "game_sgf"
  match '/records' => 'games#records', :as => :records
  match '/upload_sgf' => 'games#upload_sgf', :as => :upload_sgf
  
  match '/reset_password' => 'users#reset_password', :as => :reset_password
  match '/recover_password' => 'users#recover_password', :as => :recover_password
  match '/recovery_session' => 'sessions#recovery', :as => :recovery_session
  
  match '/confirm_email' => 'sessions#confirm_email', :as => :confirm_email
  match '/validate_email' => 'users#validate_email', :as => :validate_email

  # match '/auth', :to => 'authentications#index'
  # match '/auth/:provider/callback', :to => 'authentications#create'
  
  match '/handle_notify', :to => 'sessions#handle_notify', :as => :handle_notify
  match '/notify', :to => 'notifications#notify'
  match '/current_games', :to => 'games#current_games'
  match '/challenge', :to => 'games#gnugo_challenge', :as => :challenge
  match '/blogs' => 'broadcasts#blogs', :as => :blogs
  
  resources :broadcasts

  resources :sessions
  resources :notices
  resources :relationships, :only => [:create, :destroy]
  
  resources :users do
    resources :invitations
    resources :authentications
    member do
      get :following, :followers
    end
  end
  
  resources :games do
    resources :moves
    resources :comments
  end

  root :to => "pages#index"
  
  if ['development', 'test'].include? Rails.env
    mount Jasminerice::Engine => '/jasmine'
  end
end

app/views/shared/_errors_messages.html.erb
<% [:notice, :alert, :error].each do |key| %>
	<% if flash[key] %>
		<div class="alert-box <%= key %>"><%= flash[key] %></div>
	<% end %>
<% end %>

app/views/shared/_feed_item.html.erb
<div class="feed_show">
	<%= link_to image_tag(feed_item.thumbnail), feed_item %>
	<p>
		<span class="feed_player">
			<% black = feed_item.black_player %>
			<%= link_to black.name, black %>
		</span>
		<%= t("and") %>
		<span class="feed_player">
			<% white = feed_item.white_player %>
			<%= link_to white.name, white %>
		</span>
		<% if feed_item.status == 0 %>
			<%= t("playing_game") %>
		<% else %>
		  <%= t("finished_game") %>
		<% end %>
		<%= link_to feed_item.id, feed_item %>
		<br/>
		<span class="update_time">
			<%= time_ago_in_words feed_item.updated_at %>
		</span>
	</p>
	<p>
		<% comment = feed_item.comments.first %>
		<% if comment %>
			<% player = User.find(comment.user_id).name %>
			<%= player %>
			<%= t("says") %>
			<%= comment.content %>
		<% end %>
	</p>
	<div class="feed_link">
		<%= link_to t(".go"), feed_item, :class => 'nice black button' %>
	</div>
</div>

app/views/shared/_game_item.html.erb
<% object.each do |game| %>
<div class="game_item game_<%= game.id %>">
	<%= link_to image_tag(game.thumbnail, :class => "game_thumbnail"), game %>
	<div class="game_details <%= game.display_color(current_user) %>">
		<% if game.current_player == game.black_player %>
			<div class="game_player">
				<%= image_tag("black.png") %>
				<% if game.mode != 0 %>
					<%= game.black_player.name %>
				<% end %>
			</div>
			<div class="game_player">
				<%= image_tag("white.png") %>
				<% if game.mode != 0 %>
					<%= game.white_player.name %>
				<% end %>
			</div>
		<% else %>
			<div class="game_player">
				<%= image_tag("white.png") %>
				<% if game.mode != 0 %>
					<%= game.white_player.name %>
				<% end %>
			</div>
			<div class="game_player">
				<%= image_tag("black.png") %>
				<% if game.mode != 0 %>
					<%= game.black_player.name %>
				<% end %>
			</div>
		<% end %>
		<div class="game_update_time">
			<% if game.mode != 0 %>
				<% if game.access == 3 %>
					<%= t(:wait_for_moves) %><br/>
					<% if correct_user?(game.black_player) or correct_user?(game.white_player) %>
						<%= link_to t(:cancel), {:controller => 'games', :action => 'destroy', :id => game.id}, 
												{:method => :delete, :remote => true} %>
					<% end %>
				<% else %>
					<%= time_ago_in_words(game.updated_at) %>
					<% if game.status == 0%>
						<div class="game_status"><%= t :game_in_progress %></div>
					<% else %>
						<div class="game_status"><%= t :game_over %></div>
				  <% end %>
				<% end %>
			<% end %>
		</div>
	</div>
</div>
<% end %>

app/views/shared/_game_record.html.erb
<% object.each do |game| %>
	<div class="record_item" id="game_<%= game.id %>">
		<% if game.thumbnail %>
			<%= link_to image_tag(game.thumbnail), game_path(game), :class => "record_thumbnail" %>
		<% end %>
		<div class="record_details">
			<%= link_to game.name, game %>
			<p><%= game.created_at.to_formatted_s(:db) %></p>
			<p><%= game.brief %></p>
		</div>
	</div>
<% end %>

app/views/shared/_game_records.html.erb
<% object.each do |game| %>
	<div class="record_item" id="game_<%= game.id %>">
		<% if game.thumbnail %>
			<%= link_to image_tag(game.thumbnail), game_path(game), :class => "record_thumbnail" %>
		<% end %>
		<div class="record_details">
			<%= game.name %>
		</div>
	</div>
<% end %>

app/views/shared/_human_test.html.erb
<div id="recaptcha_widget" style="display:none">
  <div id="recaptcha_image"></div>
  <div class="recaptcha_only_if_incorrect_sol" style="color:red"><%= t :invalid_captcha %></div>
	<div class="recaptcha_inner">
		<div class="recaptcha_input">
	  	<span class="recaptcha_only_if_image"><%= t :enter_the_words_above %></span>
		  <span class="recaptcha_only_if_audio"><%= t :enter_the_numbers_you_hear %></span>
		  <input type="text" id="recaptcha_response_field" name="recaptcha_response_field" />
		</div>
		<div class="recaptcha_iconsets">
			<%= link_to image_tag("refresh.gif", :alt => t(:get_another_captcha)), "javascript:Recaptcha.reload()", :class => "recaptcha_reload" %>
			<%= link_to image_tag("audio.gif", :alt => t(:get_audio_captcha)), "javascript:Recaptcha.switch_type('audio')", :class => "recaptcha_only_if_image" %>
			<%= link_to image_tag("text.gif", :alt => t(:get_image_captcha)), "javascript:Recaptcha.switch_type('image')", :class => "recaptcha_only_if_audio" %>
			<%= link_to image_tag("help.gif", :alt => t(:help)), "javascript:Recaptcha.showhelp()", :class => "recaptcha_help" %>
		</div>
		<%= image_tag "recaptcha-icon.gif", :class => "recaptcha_logo" %>
	</div>
</div>
<%= recaptcha_tags :display => {:theme => 'custom',:custom_theme_widget => 'recaptcha_widget'} %>

app/views/shared/_notified_games.html.erb
<% if object.empty? %>
	<span class="notify_none"><%= t :none %></span>
<% else %>
	<div class="paginate" id="current_games_pagination">
		<%= paginate @current_games, :params => {:controller => 'games', :action => 'current_games', :user_id => (@user||current_user).id }, :param_name => "current_games_page", :remote => true %>
	</div>
	<div class="divider"></div>
	<div class="game_ladder">
	<% object.each do |game| %>
	<div class="notified_games_list game_<%= game.id %>">
		<% if game.thumbnail %>
			<%= link_to image_tag(game.thumbnail, :class => "game_thumbnail"), game_path(game) %>
		<% end %>
		<div class="game_details <%= game.display_color(current_user) %>">
			<% if game.current_player == game.black_player %>
				<div class="game_player">
					<%= image_tag("black.png") %>
					<% if game.mode != 0 %>
						<%= game.black_player.name %>
					<% end %>
				</div>
				<div class="game_player">
					<%= image_tag("white.png") %>
					<% if game.mode != 0 %>
						<%= game.white_player.name %>
					<% end %>
				</div>
			<% else %>
				<div class="game_player">
					<%= image_tag("white.png") %>
					<% if game.mode != 0 %>
						<%= game.white_player.name %>
					<% end %>
				</div>
				<div class="game_player">
					<%= image_tag("black.png") %>
					<% if game.mode != 0 %>
						<%= game.black_player.name %>
					<% end %>
				</div>
			<% end %>
			<div class="game_update_time">
				<% if game.mode != 0 %>
					<% if game.access == 3 %>
						<%= t(:wait_for_moves) %><br/>
						<% if correct_user?(game.black_player) or correct_user?(game.white_player) %>
							<%= link_to t(:cancel), {:controller => 'games', :action => 'destroy', :id => game.id}, {:method => :delete, :remote => true, :class => 'notice'} %>
						<% end %>
					<% else %>
						<%= time_ago_in_words(game.updated_at) %>
						<% if game.status == 0%>
							<div class="game_status"><%= t :game_in_progress %></div>
						<% else %>
							<div class="game_status"><%= t :game_over %></div>
					  <% end %>
					<% end %>
				<% end %>
			</div>
		</div>
	</div>
	<% end %>
	</div>
<% end %>

app/views/shared/_other_messages.html.erb
<% [:success, :info].each do |key| %>
	<% if flash[key] %>
		<div class="<%= key %>"><%= flash[key] %></div>
	<% end %>
<% end %>

app/views/shared/_side_bar.html.erb
<div class="notify_wrapper" id="side_bar">
	<% if user_signed_in? %>
		<% if @user %>
		<div class="notifications">
			<div class="message">
				<% broadcast = Broadcast.push_to_all.last %>
				<% if broadcast.nil? %>
					<h4>broadcasting...</h4>
				<% else %>
					<h4>
					<%= link_to broadcast.title, broadcast %>
					</h4>
					<p>
					<%= broadcast.brief %>
					</p>
				<% end %>
				<div id="all_messages"><%= link_to t('.view') + ' ' + Broadcast.count.to_s + ' ' + t('.broadcasts'), broadcasts_path %></div>
			</div>
		</div>
		<!-- <%= render 'games/pro_games' %> -->
		<% end %>
	<div class="top_bar" id="active_games">
		<div class="refresh"></div>
		<% if @user and @user != current_user %>
			<%= @user.name + t("game_of") %>
		<% else %>
			<%= t("active_games") %>
		<% end %>
	</div>
	<div id="notified_games" class="notify_content">
		<%= render('shared/notified_games', :object => @current_games) %>
	</div>
	<div id="game_duel">
		<%= link_to t(:game_duel), duel_path, :class => "nice black radius button" %>
	</div>
	<div id="game_all">
		<%= link_to t(:game_all), games_path, :class => "nice black radius button" %>
	</div>
	<% else %>
	  <%= render 'shared/signin' %>
	<% end %>
</div>

app/views/shared/_signin.html.erb
<div id="sign_in" class="notify_wrapper">
	<h2>
		<%= t("login_to_play") %>
	</h2>
	<div id="sign_in_text">
		<%= render 'sessions/new' %>
	</div>
</div>