config/routes.rb
Html5Weiqi::Application.routes.draw do
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/signin' => 'sessions#new', :as => :signin
  match '/signup' => 'users#new', :as => :signup
  match '/duel' => 'games#duel', :as => :duel
  match '/watch' => 'games#index', :as => :index
  match '/games/laoqipan_:id.sgf' => 'games#sgf', :format => "sgf", :as => "game_sgf"
  match '/records' => 'games#records', :as => :records
  match '/upload_sgf' => 'games#upload_sgf', :as => :upload_sgf
  
  match '/reset_password' => 'users#reset_password', :as => :reset_password
  match '/recover_password' => 'users#recover_password', :as => :recover_password
  match '/recovery_session' => 'sessions#recovery', :as => :recovery_session
  
  match '/confirm_email' => 'sessions#confirm_email', :as => :confirm_email
  match '/validate_email' => 'users#validate_email', :as => :validate_email

  # match '/auth', :to => 'authentications#index'
  # match '/auth/:provider/callback', :to => 'authentications#create'
  
  match '/handle_notify', :to => 'sessions#handle_notify', :as => :handle_notify
  match '/notify', :to => 'notifications#notify'
  match '/current_games', :to => 'games#current_games'
  match '/challenge', :to => 'games#gnugo_challenge', :as => :challenge
  match '/blogs' => 'broadcasts#blogs', :as => :blogs
  
  resources :broadcasts

  resources :sessions
  resources :notices
  resources :relationships, :only => [:create, :destroy]
  
  resources :users do
    resources :invitations
    resources :authentications
    member do
      get :following, :followers
    end
  end
  
  resources :games do
    resources :moves
    resources :comments
  end

  root :to => "pages#index"
  
  if ['development', 'test'].include? Rails.env
    mount Jasminerice::Engine => '/jasmine'
  end
end

app/models/game.rb
# @mode : 0 => uploads, 1 => modern style game, 2 => traditional style game
# @status : 0 => on going game, 1 => finished game
# @access : 0 => public, 1 => private, 3 => protected
class Game < ActiveRecord::Base
  attr_accessible :sgf, :moves, :mode, :access, :status, :name, :score_requester,
                  :current_player, :black_player, :white_player, :opponent, :uploader,
                  :brief
  attr_accessor :opponent
                  
  belongs_to :current_player, :class_name => "User"
  belongs_to :black_player, :class_name => "User"
  belongs_to :white_player, :class_name => "User"
  has_many :comments, :order => "created_at DESC"
  belongs_to :uploader, :class_name => "User"

  validates_inclusion_of :mode, :in => [0, 1 ,2]
  validates_inclusion_of :status, :in => [0, 1]
  
  validates_presence_of :sgf, :on => :create, :message => I18n.t(:no_sgf_msg)
  validates_length_of :sgf, :maximum => 1.megabyte, :on => :create, :message => I18n.t(:sgf_length_msg)
  
  scope :feed_items, where("mode != 0 and access = 0").order("updated_at DESC")
  scope :records, where("mode = 0").order("updated_at DESC")
  scope :current_games, lambda { |user_id| where("black_player_id = '#{user_id}' or white_player_id = '#{user_id}'").order("case when status = 3 then 0 when status = 0 then 1 else 2 end, case when current_player_id = '#{user_id}' then 0 else 1 end, status, updated_at DESC")}
  scope :uploads, where("mode = 0").order('created_at DESC')
  
  def thumbnail_path
    dir = File.expand_path("public/system/thumbnails", Rails.root.to_s)
    year, month, day = self.created_at.year, self.created_at.month, self.created_at.day
    dir = dir + "/#{year}/#{month}/#{day}"
    FileUtils.makedirs(dir)
    
    path = dir+"/#{self.id}.png"

    return path
  end
  
  def thumbnail
    path = "/system/thumbnails/#{self.created_at.year}/#{self.created_at.month}/#{self.created_at.day}/#{self.id}.png"
    if File.exists?("#{Rails.root.to_s}/public#{path}")
      return path + "?#{self.updated_at.to_s(:number)}"
    else
      return "default_board.png"
    end
  end
  
  def display_color(user)
    if current_player == user and status != 1
      "my_turn"
    else
      "others_turn"
    end
  end
  
  def vs_ai?
    black_player.robot? || white_player.robot?
  end
  
  def who_is_ai
    if black_player.robot?
      black_player
    elsif white_player.robot?
      white_player
    end
  end
  
  def continue_move_if_ai
    color = current_player == black_player ? 'black' : 'white'
    Stalker.enqueue("ai_move", :game_id => id, :game_sgf => sgf, :color => color)
  end
  
  scope :from_users_followed_by, lambda { |user| followed_by(user) }
  
  private
  
    def self.followed_by(user)
      followed_ids = %(SELECT followed_id FROM relationships WHERE follower_id = :user_id)
      where("black_player_id IN (#{followed_ids}) OR white_player_id IN (#{followed_ids})", {:user_id => user}).order("updated_at DESC")
    end
end

# == Schema Information
#
# Table name: games
#
#  id                :integer         not null, primary key
#  sgf               :text
#  name              :string(255)
#  mode              :integer         default(0)
#  current_player_id :integer
#  status            :integer         default(0)
#  black_player_id   :integer
#  white_player_id   :integer
#  created_at        :datetime
#  updated_at        :datetime
#  access            :integer         default(3)
#  score_requester   :integer         default(0)
#  uploader          :integer
#  brief             :text
#

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_filter :authenticate_user!, :only => [:new, :create, :gnugo_challenge]
  before_filter :authenticate?, :only => [:destroy]
  before_filter :qualified?, :only => :new
  before_filter :only => [:edit, :update] { authenticate_admin(root_url) }
  
  def index
    respond_to do |format|
      format.html { @feed_items = Game.feed_items.page(params[:page]).per(10) }
      format.js { @games = Game.feed_items.page(params[:game_page]).per(10)}
    end
  end
  
  def records
    @games = Game.records.page(params[:page]).per(24)
    
    respond_to do |format|
      format.html
    end
  end

  def show
    begin
      @game = Game.find(params[:id])
      @comments = @game.comments.page(params[:comments_page]).per(9)
      
      if user_signed_in?
        @current_games = Game.current_games(current_user.id).page(params[:current_games_page]).per(4)
        @users = User.on_play_list(current_user.id).page(params[:page]).per(19)
      else
        @users = User.where("open_for_play = true").order("last_request_at DESC").page(params[:page]).per(19)
      end
    rescue ActiveRecord::RecordNotFound
      redirect_to root_url
      return
    end
    
    respond_to do |format|
      format.html
    end
  end

  def new
    @game = Game.new
    respond_to do |format|
      if params[:opponent]
        @opponent_name = params[:opponent]
        @game.opponent = @opponent_name
        if current_user == User.find_by_name(@opponent_name)
          format.html {render :text => I18n.t(:cannot_duel_with_yourself), :status => 403}
        else
          format.html
        end
      else
        format.html { render :text => I18n.t(:chose_opponent_msg), :status => 500 }
      end
    end
  end

  def create
    @attr = params[:game] || {}
    mode = @attr[:mode] || "0"
    @pb = @pw = @pc = nil
    @sgf = nil

    if mode == "0"
      if params[:sgf_url] != ""
        require 'sgf'
        sgf_url = params[:sgf_url]
        fetched_sgf = fetch_tom_sgf(sgf_url)

        @attr.merge!({:sgf => fetched_sgf,
                      :mode => 0, 
                      :access => 3})
      elsif params[:raw_sgf] != ""
        @attr.merge!({:sgf => params[:raw_sgf],
                      :mode => 0,
                      :access => 3})
      end
      
      @game = Game.new(@attr)
      if @game.save
        Stalker.enqueue('generate_thumbnail', :game_id => @game.id, :game_sgf => @game.sgf, :thumb_path => @game.thumbnail_path)
        redirect_to(game_path(@game))
      else
        flash.now[:alert] = t(:failed_to_create_game)
        render :action => :upload_sgf
      end
    else
      if mode == "1"
        @pc = @pb = User.find_by_name(@attr[:opponent])
        @pw = current_user
        @sgf = "(;FF[4]GM[1]SZ[19]RU[Japanese]KM[6.5]PB[#{@pb.name}]PW[#{@pw.name}])"
      elsif mode == "2"
        @pc = @pw = User.find_by_name(@attr[:opponent])
        @pb = current_user
        @sgf = "(;FF[4]GM[1]SZ[19]RU[Chinese]KM[0]HA[2]PB[#{@pb.name}]PW[#{@pw.name}]AB[pd][dp]AW[dd][pp])"
      end
      
      if @pw == @pb
        flash[:error] = I18n.t(:cannot_duel_with_yourself)
        respond_to do |format|
          format.html { render :text => "can't duel with yourself", :status => 403 }
        end
        return
      end
    
      @attr.merge!({:black_player => @pb, 
                    :white_player => @pw,
                    :current_player => @pc,
                    :sgf => @sgf})
      @game = Game.create(@attr)
      
      respond_to do |format|
        if @game.save
          if @game.status == 0 and @game.current_player.robot?
            color = @game.current_player == @game.black_player ? 'black' : 'white'
            Stalker.enqueue("ai_move", :game_id => @game.id, :game_sgf => @game.sgf, :color => color)
          end
          format.html { redirect_to game_url(@game) }
        else
          format.html { render :text => "failed to create game", :status => 500 }
        end
      end
    end
  end
  
  def edit
    @game = Game.find(params[:id])
  end
  
  def update
    @game = Game.find(params[:id])
    @attr = params[:game]
    
    respond_to do |format|
      if @game.update_attributes(@attr)
        format.html { redirect_to @game }
      else
        format.html { render :action => 'edit' }
      end
    end
  end
  
  def destroy
    @game = Game.find(params[:id])
    @game.destroy
    @current_games = current_user.current_games
    respond_to do |format|
      format.js
    end
  end
  
  def authenticate?
    @game = Game.find(params[:id])
    if (!user_signed_in?)
      redirect_to root_url and return
    end
    
    if (current_user != @game.black_player) && (current_user != @game.white_player)
      redirect_to user_path(current_user), :alert => I18n.t(:access_denied) and return
    end
    
    if @game.access != 3
      redirect_to user_path(current_user), :alert => I18n.t(:access_denied) and return
    end
  end
  
  def duel
    @robot = User.where('role=98').first
    if user_signed_in?
      @users = User.where("id != #{current_user.id} and open_for_play = true and role != 98").order("last_request_at DESC").page(params[:page]).per(20)
    else
      @users = User.where("open_for_play = true and role != 98").order("last_request_at DESC").page(params[:page]).per(20)
    end
    
    respond_to do |format|
      format.html
    end
  end
  
  def sgf
    @game = Game.find_by_id(params[:id])
    render :text => @game.sgf, :content_type => 'application/x-go-sgf'
  end
  
  def upload_sgf
    @game = Game.new(:mode => 0)
    
    respond_to do |format|
      format.html
    end
  end
  
  def current_games
    if params[:user_id]
      user = User.find(params[:user_id])
    else
      user = current_user
    end
    
    @current_games = Game.current_games(user.id).page(params[:current_games_page]).per(4)
    
    respond_to do |format|
      format.js
    end
  end
  
  def gnugo_challenge
    @game = Game.new
    opponent = User.where("role = 99 or role = 98").first
    @opponent_name = opponent.name
    respond_to do |format|
      format.html
    end
  end
  
  def qualified?
    if current_user.level == 0
      redirect_to challenge_url, :alert => I18n.t(:need_qualification)
    end
  end
  
end

app/helpers/games_helper.rb
module GamesHelper
  def game_div(game, &block)
    if !game.nil?
      options = {
        "id"             => "game",
        "sgf"            => game.sgf,
        "mode"           => game.mode,
        "access"         => game.access,
        "status"         => game.status,
        "current_player" => game.current_player.id,
        "black_player"   => game.black_player.id,
        "white_player"   => game.white_player.id,
        "requester"      => game.score_requester,
        "channel"        => game.id
      }
    
      @cur = current_user.id if current_user
      options.merge!(:current_user => @cur)
    else
      options = {
        "id"    => "game",
      }
    end
    
    content_tag(:div, options, &block)
  end
  
end

app/views/games/_form.html.erb
<%= form_for @game do |f| %>
	<div class="field">
  	<%= f.label :sgf, "SGF text (can be blank)" %><br />
		<%= f.text_area :sgf %>
	</div>

	<div class="field">
		<%= f.label :name, t(".game_name") %><br><%= f.text_field :name %>
	</div>
	
	<div class="field">
		<%= f.label :brief %><br>
		<%= f.text_area :brief %>
	</div>
	
	<div class="field">
		<%= f.submit %>
	</div> 	
<% end %>

app/views/games/_game_comments.html.erb
<% if !@comments.nil? %>
<div id="comments">
	<%= render :partial => "comments/comment", :collection => @comments %>
</div>
<div class="paginate">
	<%= paginate @comments, :params => { :controller => :comments, :action => 'index', :game_id => @game.id }, :param_name => :comments_page, :remote => true %>
</div>
<% end %>
<div class="divider"></div>
<div id="post_comments">
	<% if user_signed_in? and !@game.nil? %>
		<%= form_for ([@game, @game.comments.build]), :remote => true do |f| %>
		  <%= f.text_field :content, :id => "post_in" %>
			<%= f.submit t(".post") %>
			<span class="tips"><%= t ".post_tips" %></span>
		<% end %>
	<% else %>
	  <span><%= t ".post_off" %></span>
	<% end %>
</div>

app/views/games/_new.html.erb
<% opponent = User.find_by_name(@game.opponent) %>
<%= form_for @game, :remote => true do |f| %>
	<div class="field">
		<%= f.label :opponent, t(:your_opponent)+@opponent_name %>
		<%= f.hidden_field :opponent  %>
	</div>

	<div class="field">
		<%= f.label :mode, t(:select_mode) %>
		<%= f.select :mode, [[t(:old_style), 2], [t(:modern_style), 1]] %>
	</div>

	<div class="field">
		<%= f.submit t(:send) %>
	</div>
<% end %>

app/views/games/_pro_game_show.html.erb
<div id="progame_board">
	<div id="game_review" sgf="<%= @game.sgf %>" channel="<%= @game.id %>" mode="<%= @game.mode %>">
  <%= render "games/analyse_board" %>
	</div>
	<div class="divider"></div>
	<%= render 'tab_info' %>
</div>
<div id="progame_info">
	<div id="progame_ev"></div>
	<div>
		<%= image_tag('black_stone.png') %>
		<div id="progame_black"></div>
	</div>
	<div>
		<%= image_tag('white_stone.png') %>
		<div id="progame_white"></div>
	</div>
	<div>
		<span id="progame_date"></span><span id="progame_result"></span>
	</div>
	<div id="sgf_comments"></div>
	<% if user_signed_in? and current_user.admin? %>
		<%= link_to t('.edit'), edit_game_path(@game) %>
	<% end %>
</div>

app/views/games/_pro_games.html.erb
<div id="topic_bar">
	<% if !@pro_game.nil? %>
		<h3>
			<%= t :pro_games_view %>
			<%= link_to t('.all_records'), records_path %>
		</h3>
		<div>
			<%= link_to image_tag(@pro_game.thumbnail), @pro_game %>
			<p>
				<%= @pro_game.brief %>
				<%= link_to t('.go'), @pro_game %>
			</p>
		</div>
	<% end %>
	<% if user_signed_in? and current_user.admin? %>
		<div class="clear"><%= link_to t('.new_sgf_game'), upload_sgf_path %></div>
	<% else %>
		<div class="divider"></div>
	<% end %>
</div>

app/views/games/create.js.erb
$('#game_area').html("<%= escape_javascript(render("games/the_game")) %>");
$('#comment_box').html("<%= escape_javascript(render("games/game_comments")) %>");
prepare_game()
init_game();
window.board_game_id = "<%= @game.id %>"
if ($('#player_list').is(':visible')) {
	$('#player_list').hide();
}

app/views/games/current_games.js.erb
$("#notified_games").html("<%= escape_javascript(render('shared/notified_games', :object => @current_games)) %>");
$('#current_games_pagination').html("<%= escape_javascript(paginate(@current_games, :param_name => :current_games_page, :remote => true).to_s) %>");
window.hideLoader($('#notified_games'));
  

app/views/games/duel.html.erb
<div class="select_player">
	<% if user_signed_in? and current_user.level == 0 %>
		<div class="alert-box warning">
		<%= t(:need_qualification) %>
		</div>
		<div class="alert-box">
		<%= link_to t(:take_the_challenge), challenge_path %>
		</div>
		<div class="divider"></div>
	<% end %>
	<h3><%= t :select_player %></h3>
	<%= render "users/list", :object => @users %>
	<div class="divider"></div>
	<div class="pagination">
		<%= paginate @users %>
	</div>
</div>
<div class="divider"></div>

app/views/games/edit.html.erb
<h1>edit</h1>

<%= render "form" %>

<%= link_to "Back", games_path %>

app/views/games/gnugo_challenge.html.erb
<div class="game_new">
	<% flash.each do |name, msg| %>
		<%= content_tag :div, msg, :class => "#{name}" if msg.is_a?(String) %>
	<% end %>
	<%= form_for @game, :class => "nice" do |f| %>
			<%= f.label :opponent, t(:your_opponent)+@opponent_name %>
			<%= f.hidden_field :opponent, :value => @opponent_name  %>

			<p>
			<%= f.label :mode, t(:select_mode) %>

			<%= f.radio_button :mode, 1, :checked => true %><span><%= t(:modern_style) %></span><br/>

			<%= f.radio_button :mode, 2 %><span><%= t(:old_style) %></span><br/>
			</p>

			<%= f.submit t(:send) %>
	<% end %>

	<%= link_to t("back_to_select"), duel_path %>
</div>

app/views/games/index.html.erb
<% unless @feed_items.empty? %>
	<div class="game_index">
		<%= render :partial => 'shared/feed_item', :collection => @feed_items %>
		<div class="paginate">
			<%= paginate @feed_items %>
		</div>
	</div>
<% end %>

app/views/games/index.js.erb
$('#games_list').html("<%= escape_javascript(render('games/index')) %>");
window.hideLoader($('#games_list'));

app/views/games/records.html.erb
<%= render 'shared/game_record', :object => @games %>

app/views/games/show.html.erb
<div class="relative">
	<% if @game.mode != 0 %>
	<div id="game_area"><%= render "games/the_game" %></div>
	<div id="discussion"><%= render "games/tab_info" %></div>
	<div id="game_review" title="<%= t(:analyse) + t(:analyse_tips) %>">
		<%= render "games/analyse_board" %>
	</div>
	<%= render "shared/side_bar" %>
	<% else %>
		<%= render 'pro_game_show' %>
	<% end %>
</div>