config/routes.rb
Html5Weiqi::Application.routes.draw do
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/signin' => 'sessions#new', :as => :signin
  match '/signup' => 'users#new', :as => :signup
  match '/duel' => 'games#duel', :as => :duel
  match '/watch' => 'games#index', :as => :index
  match '/games/laoqipan_:id.sgf' => 'games#sgf', :format => "sgf", :as => "game_sgf"
  match '/records' => 'games#records', :as => :records
  match '/upload_sgf' => 'games#upload_sgf', :as => :upload_sgf
  
  match '/reset_password' => 'users#reset_password', :as => :reset_password
  match '/recover_password' => 'users#recover_password', :as => :recover_password
  match '/recovery_session' => 'sessions#recovery', :as => :recovery_session
  
  match '/confirm_email' => 'sessions#confirm_email', :as => :confirm_email
  match '/validate_email' => 'users#validate_email', :as => :validate_email

  # match '/auth', :to => 'authentications#index'
  # match '/auth/:provider/callback', :to => 'authentications#create'
  
  match '/handle_notify', :to => 'sessions#handle_notify', :as => :handle_notify
  match '/notify', :to => 'notifications#notify'
  match '/current_games', :to => 'games#current_games'
  match '/challenge', :to => 'games#gnugo_challenge', :as => :challenge
  match '/blogs' => 'broadcasts#blogs', :as => :blogs
  
  resources :broadcasts

  resources :sessions
  resources :notices
  resources :relationships, :only => [:create, :destroy]
  
  resources :users do
    resources :invitations
    resources :authentications
    member do
      get :following, :followers
    end
  end
  
  resources :games do
    resources :moves
    resources :comments
  end

  root :to => "pages#index"
  
  if ['development', 'test'].include? Rails.env
    mount Jasminerice::Engine => '/jasmine'
  end
end

app/models/broadcast.rb
class Broadcast < ActiveRecord::Base
  belongs_to :user, :foreign_key => 'author'
  
  scope :push_to_all, where(:push => true)
end


# == Schema Information
#
# Table name: broadcasts
#
#  id         :integer         not null, primary key
#  title      :string(255)
#  body       :text
#  brief      :text
#  author     :integer
#  created_at :datetime
#  updated_at :datetime
#  push       :boolean
#

app/controllers/broadcasts_controller.rb
class BroadcastsController < ApplicationController
  before_filter :except => [:index, :show] { authenticate_admin(broadcasts_url) }
  
  def index
    @broadcasts = Broadcast.push_to_all.order('created_at DESC').page(params[:page]).per(5)
    
    respond_to do |format|
      format.html
    end
  end
  
  def show
    @broadcast = Broadcast.find(params[:id])
    
    respond_to do |format|
      format.html
    end
  end
  
  def new
    @broadcast = Broadcast.new
    
    respond_to do |format|
      format.html
    end
  end
  
  def create
    @attr = params[:broadcast]
    @attr.merge!(:author => current_user.id)
    @broadcast = Broadcast.new(params[:broadcast])
    
    respond_to do |format|
      if @broadcast.save
        format.html { redirect_to @broadcast }
      else
        format.html { render action: 'new' } 
      end
    end
  end
  
  def edit
    @broadcast = Broadcast.find(params[:id])
  end
  
  def update
    @attr = params[:broadcast]
    @broadcast = Broadcast.find(params[:id])
    
    respond_to do |format|
      if @broadcast.update_attributes(@attr)
        format.html { redirect_to @broadcast }
      else
        flash.now[:alert] = @broadcast.errors.full_messages
        format.html { render action: 'edit' }
      end
    end
  end
  
  def destroy
    @broadcast = Broadcast.find(params[:id])
    @broadcast.destroy
    
    respond_to do |format|
      format.html { redirect_to broadcasts_url }
    end
  end
  
  def blogs
    @broadcasts = Broadcast.order('created_at DESC').page(params[:page]).per(5)
    
    respond_to do |format|
      format.html { render :index }
    end
  end
end

app/helpers/broadcasts_helper.rb
require 'code_formatter'

module BroadcastsHelper
  def markdown(text)
    CodeFormatter.new(text).to_html.html_safe
    # syntax_on(content).html_safe
  end
  
  def syntax_on(html)
    html.gsub(/\<code( class="(.+?)")?\>(.+?)\<\/code\>/m) do
          CodeRay.scan($3, $2).div(:line_numbers => :table)
    end
  end
end

app/views/broadcasts/_form.html.erb
<%= form_for @broadcast do |f| %>
  <div class="field">
		<%= f.label :title %>
		<%= f.text_field :title %>
	</div>
	
	<div class="field">
		<%= f.label :brief %>
		<%= f.text_field :brief %>
	</div>
	
	<div class="field">
		<%= f.label :body %>
		<%= f.text_area :body %>
	</div>
	
	<div class="field">
		<%= f.label :push %>
		<%= f.check_box :push, {}, true, false %>
	</div>
	
	<div class="field">
		<%= f.submit t(:post) %>
	</div>
<% end %>

app/views/broadcasts/edit.html.erb
<%= render 'form' %>

app/views/broadcasts/index.html.erb
<div class="meta">
<% if user_signed_in? and current_user.admin? %>
	<%= link_to t('.new_broadcast'), new_broadcast_path %>
<% end %>
</div>

<div class="broadcasts">
	<% @broadcasts.each do |b|%>
		<div class="blog">
			<h1><%= link_to b.title, b %></h1>
			<div class="blog_meta">
				<span>
					<%= image_tag 'pen.png' %>
					<%= b.user.name %>
				</span>
				<%= b.created_at.to_s(:db) %>
			</div>
			<div class="brief"><%= b.brief %></div>
			<div class="blog_body">
				<%= markdown b.body %>
			</div>
		</div>
	<% end %>
	<%= paginate @broadcasts %>
</div>

app/views/broadcasts/new.html.erb
<%= render 'form' %>

app/views/broadcasts/show.html.erb
<div class="side_nav">
	<p><%= link_to t('.view') + ' ' + Broadcast.push_to_all.count.to_s + ' ' + t('.broadcasts'), broadcasts_path %></p>
	<p><%= link_to t('.view') + ' ' + Broadcast.count.to_s + ' ' + t('.blogs'), blogs_path %></p>
</div>

<div class="blog">
	<h1><%= @broadcast.title %></h1>
	<div class="blog_meta">
		<span>
			<%= image_tag 'pen.png' %>
			<%= @broadcast.user.name %>
		</span>
		<%= @broadcast.created_at.to_s(:db) %>
		<% if user_signed_in? and current_user.admin? %>
			<%= link_to 'edit', edit_broadcast_path(@broadcast) %>
			<%= link_to 'delete', @broadcast, :method => :delete, :confirm => "continue?" %>
		<% end %>
	</div>
	<div class="brief"><%= @broadcast.brief %></div>
	<div class="blog_body">
		<%= markdown @broadcast.body %>
	</div>
</div>